baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Techtious Blog'
theme = "ananke"
[taxonomies]
  tag = "tags"
  category = "categories"
[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 3
