baseURL = 'https://blog.techtious.com/'
languageCode = 'en-us'
title = 'Techtious Blogs'
theme = "ananke"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  custom_css = ["css/custom.css"]   #