baseURL = 'https://techtious.com/'
languageCode = 'en-us'
title = 'Techtious'
theme = "ananke"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  custom_css = ["css/custom.css"]
  techtiousBaseURL = "https://techtious.com/"
  show_reading_time = true
  site_logo = "Logo.svg"
  background_color_class = "bg-white"