name: Build & Deploy Hugo Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      # 4️⃣ Save Docker image as a tar
      - name: Save Docker image
        run: docker save ${{ secrets.DOCKER_IMAGE_NAME }} -o hugo-site.tar

      # 5️⃣ Copy image tar to server via SSH
      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hugo-site.tar"
          target: "/tmp/hugo-site.tar"

      # 6️⃣ Load Docker image and run container on server
      - name: Deploy Docker image on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop previous container if exists
            docker rm -f ${{ secrets.DOCKER_IMAGE_NAME }} || true

            # Remove old image
            docker rmi ${{ secrets.DOCKER_IMAGE_NAME }} || true

            # Load new image
            docker load -i /tmp/hugo-site.tar

            # Run container
            docker run -d --name ${{ secrets.DOCKER_IMAGE_NAME }} -p 80:80 --restart unless-stopped ${{ secrets.DOCKER_IMAGE_NAME }}
